acronym_list = {
#technical twitter abbreviations
"dm" : "direct message",
"ct" : "cuttweet",
"rt" : "retweet", 
#"prt" : "partial retweet",
"mt" : "modified tweet",
"prt" : "please retweet", 
#"ht" : "hat tip",
"cc" : "carbon copy",
"cx" : "correction",
#industry twitter abbreviations
"em" : "email marketing",
"seo" : "search engine optimization",
"sroi" : "social return on investment",
"sn" : "social network",
"yt" : "youtube",
"ugc" : "user generated content",
"smo" : "social media optimization",
"fb" : "facebook",
"li" : "linkedin",
 "sm" : "social media",
 "smm" : "social media marketing",
 "ezine" : "electronic magazine",
#conversational twitter abbreviations
 "bgd" : "background",
 "cd9":"parents are around",
 #"cd9":"code 9"
 "btw" : "by the way",
 "ab" : "about",
 "abt" : "about",
 "dd" : "dear daughter",
 "afaik" : "as far as i know",
 "ayfkmwts" : "are you fucking kidding me?",#"are you fucking kidding me with this s—?"
"br" : "best regards",
 "chk" : "check",
 "cul dp" : "profile picture",
 #"fml" : "family life",
 "fubar" : "fucked up beyond all repair", # (slang from the us military)
 "bh" : "bye for now",
 "bbfn" : "bye for now",
 "b4":"before",
 "ds" : "dear son",
 "ff" : "follow friday",
 "ema" : "email address",
 #"dyk" : "did you know", 
 "dyk":"do you know",
 "f": "buddy",
 "hagn" : "have a good night",
 "df" : "dear fiance",
 "dam" : "don’t annoy me",
 "ffs" : "for fuck‘s sake",
 "eml" : "email",
 "fotd" : "find of the day",
 "ftw" : "for the win",
 "fwiw" : "for what it’s worth",
 #"hth" : "hope that helps",
 "gmafb" : "give me a fucking break",
 "hand" : "have a nice day",
 "hella":"hell of a",
 "icymi" : "in case you missed it",# a quick way to apologize for retweeting your own material
 "gtfooh" : "get the fuck out of here",
 "gts" : "guess the song",
 "hotd" : "headline of the day",
 "iirc" : "if i remember correctly",
 "kyso" : "knock your socks off",
 "kk" : "got it",#kewl kewl, or ok, "got it"
 "ht" : "heard through",
 "ic" : "i see",
 "idk" : "i do not know",
 "lhh" : "laugh hella hard", #(a stronger version of lol)
 #"zomg" : "omg to the max"
 "imho" : "in my humble opinion",
 "nfw" : "no fucking way",
 "orly" : "oh, really?",
 "yoyo" : "you are on your own",
 "iwsn" : "i want sex now",
 "lmao" : "laughing my ass off",
 "irl" : "in real life",
 "jk" : "just kidding",#joke
 "jv" : "joint venture",
 "lo" : "little one",
 "lol" : "laugh out loud",
 "mm" : "music monday",
 "lmk" : "let me know",
 "jsyk" : "just so you know",
 "nsw" : "not safe work",
 "nsfw" : "not safe for work",
 "mrjn" : "marijuana",
 "oh" : "overheard",
 "mirl" : "meet in real life",
 "nct" : "nobody cares, though",
 "rlrt" : "reallife retweet",#a close cousin to oh
 "nbd" : "no big deal",
 "njoy" : "enjoy",
 "omfg" : "oh my fucking god",
 "pnp" : "party and play",#(drugs and sex)
 "qotd" : "quote of the day",
 "re" : "in reply to",#in regards to
 "rtq" : "read the question",
 "sfw" : "safe for work",
 "oomf" : "one of my friends, followers",
 "nts" : "note to self",
 "rtfm" : "read the fucking manual",
 "snafu" : "situation normal, all fucked up", #(slang from the us military)
 "smh" : "shaking my head",
 "stfw" : "search the fucking web!",
 "tftt" : "thanks for this tweet",
 "sob" : "son of a bitch",#b--
 "tftf" : "thanks for the follow",
 "so" : "significant other",
 "tj" : "tweetjack",# or joining a conversation belatedly to contribute to a tangent
 "ty" : "thank you",
 "srs" : "serious",
 "smdh" : "shaking my damn head",#smh, only more so
 "stf" : "shut the fuck",
 "stfu" : "shut the fuck up!",
 "tl" : "timeline",
 "tyia" : "thank you in advance",
 "tt" : "trending topic",
 "w": "with",
 "/w": "with",
 "tldr" : "too long did not read",
 "tl;dr" : "too long did not read",
"tmb" : "tweet me back",
 "tyvw" : "thank you very much",
 "wtv" : "whatever",
 "ymmv" : "your mileage may vary",
 "yw" : "you are welcome",
 "ykyat" : "you know you are addicted to",
 #"w/e or we" : "whatever or weekend"
 "we" : "weekend",
 "w/e" : "whatever",
 "tyt" : "take your time",
 "ykwim" : "you know what i mean",
 "yolo" : "you only live once",
 "ygtr" : "you got that right",
 "ama" : "ask me anything",
"brb" : "be right back",
"btaim" : "be that as it may",
"bts" : "behind the scenes",
"dae" : "does anyone else?",
"fbf" : "flashback friday",
"fbo" : "facebook official",
"fomo" : "fear of missing out",
"ftfy" : "fixed that for you",
"ftw" : "for the win",
"fyi" : "for your information",
"hth" :"happy to help",
"idc" : "i do not care",
"idk" : "i do not know",
"ikr" : "i know, right?",
"ily" : "i love you",
"imo" : "in my opinion",
"irl" : "in real life",
"lmk" : "let me know",
"lms" : "like my status",
"mcm" :"man crush monday",
"mfw" : "my face when…",
"mtfbwy" : "may the force be with you",
"nbd" : "no big deal",
"nm" : "not much",
"nvm" : "never mind",
"omw" : "on my way",
"ootd" : "outfit of the day",
"op" : "original poster",
"otp" : "one true pairing",
"ppl" : "people",
"rofl" : "rolling on the floor laughing",
"roflmao" : "rolling on the floor laughing my ass off",
"smh" : "shaking my head",
"tbh" : "to be honest",
"tbbh" : "to be brutally honest",
"tbt" : "throwback thursday",
"tfw" : "that feeling when….",
"tgif" : "thank god it’s friday",
"til" : "today i learned…",
"tmi" : "too much information",
"wbuv" : "what about you?",
"wbw" : "way back wednesday",
"wfh" : "work from home",
"b/c":"because",
"br":"best regards",
"fml":"fuck my life",
"ftf": "face to face",
"ftl":"for the loss",
#"ftw":"for the win"
"fwd":"forward",
"wtf":"what the fuck",
"wth":"what the hell",
"&amp":"and",
#have to include more slangs like below
"kinda": "kind of",
"wanna": "want to",
"gonna": "going to",
"haveta": "have to",
"gotta": "got to",
"coulda": "could have",
"shoulda": "should have",
"woulda": "would have",
"musta": "must have",
"hafta": "have to",
"lotsa": "a lot of",
"lotsa": "a lot of",
"sorta": "sort of",
}
