emoji_sentiment = {'😷': -1,
                   '❤': 1,
                   '😉': 1,
                   '♥': 1,
                   '😂': 1,
                   '😳': -1,
                   '💫': 1,
                   '😭': -1,
                   '😔': -1,
                   '☺': 1,
                   '😩': -1,
                   '😘': -1,
                   '😊': 1,
                   '😆': 1,
                   '🌟': 1,
                   '⛄': 1,
                   '😚': -1,
                   '😅': 1,
                   '👍': 1,
                   '😏': -1,
                   '😯': 1,
                   '😒': -1,
                   '💃': 1,
                   '😡': -1,
                   '🎂': 1,
                   '🎉': 1,
                   '👋': 1,
                   '😎': 1,
                   '😜': 1,
                   '👌': 1,
                   '😍': 1,
                   '💚': 1,
                   '💕': 1,
                   '😁': -1,
                   '👏': 1,
                   '🍷': 1,
                   '💛': 1,
                   '😄': 1,
                   '✅': 1,
                   '😝': 1,
                   '😺': 1,
                   '🎁': 1,
                   '😞': -1,
                   '😥': -1,
                   '☹': -1,
                   '💯': 1,
                   '😢': -1,
                   '💗': 1,
                   '✌': 1,
                   '😫': -1,
                   '💟': -1,
                   '😬': -1,
                   '💜': 1,
                   '😃': 1,
                   '😵': -1,
                   '👭': 1,
                   '🙀': 1,
                   '😀': 1,
                   '👎': -1,
                   '💞': 1,
                   '😤': -1,
                   '💖': 1,
                   '😋': 1,
                   '😴': -1,
                   '😦': -1,
                   '😓': -1,
                   '😗': 1,
                   '💔': -1,
                   '😐': -1,
                   '😨': -1,
                   ':)': 1,
                   ':(': -1,
                   ':P': 1,
                   ';)': 1,
                   '(y)': 1}

popular_emoji = ['😂',
                 '😭',
                 '😔',
                 '☺',
                 '😩',
                 '😘',
                 '😆',
                 '😚',
                 '👍',
                 '😏',
                 '😒',
                 '😡',
                 '😎',
                 '😜',
                 '😍',
                 '😄',
                 '😝',
                 '😞',
                 '☹',
                 '😢',
                 '😫',
                 '😬',
                 '😃',
                 '😴',
                 '😓',
                 '😗',
                 '💔',
                 '😐',
                 ':)',
                 ':(',
                 ':P',
                 ';)',
                 '(y)', ]
#interjections = ['wow', 'haha', 'lol', 'laugh out loud', 'rofl', 'lmao', 'kidding', 'wtf', 'duh','ha ha']
#Added by Arifur Rahaman
interjections = ['ah', 'aha', 'aww','nah','wew','yay','uh', 'awesome' , 'bah', 'bingo', 'boo', 'bravo', 'brilliant'
                 ,'brrr', 'duck', 'excellent', 'fabulous', 'fantastic', 'fore', 'great', 'ha-ha', 'ho-ho', 'ho-ho-ho'
                 , 'ick', 'marvelous', 'my goodness', 'nuts', 'oh', 'ouch', 'ow', 'shh', 'super', 'yippee', 'yummy', 'big deal']
#Added by Arifur Rahaman
laughter_list = ['lol',"lhh", 'laugh out loud',"jk",'wow', 'kidding', 'ha ha', 'ha-ha','haha', 'rofl','roflmao', 'lmao', 'wtf']
#Added by Arifur Rahaman
laughter_emoji = [
                   '😉',
                   '😂',
                   '💫',
                   '☺',
                   '😊',
                   '😆',
                   '🌟',
                   '⛄',
                   '😅',
                   '👍',
                   '😯',
                   '💃',
                   '🎂',
                   '🎉',
                   '👋',
                   '😎',
                   '😜',
                   '👌',
                   '😍',
                   '👏',
                   '🍷',
                   '😄',
                   '😝',
                   '😺',
                   '🎁',
                   '✌',
                   '😃',
                   '👭',
                   '🙀',
                   '😀',
                   '😋',
                   '😗',
                   ':)',
                   ':P',
                   ';)',
                   '(y)']
exclude = ['I', 'U.S', 'RT','FAV','VIA']
#''
intensifier_list = ['absolutely', 'almost', 'amazingly', 'astoundingly', 'awful', 'awfully', 'barely', 'bitterly',
                    'bloody', 'colossally', 'completely', 'considerably', 'crazy', 'dangerously', 'decidedly',
                    'deeply', 'dreadfully', 'easily', 'effing', 'enormously', 'entirely', 'especially',
                    'exceptionally', 'excessively', 'extraordinarily', 'extremely', 'fairly', 'fantastically',
                    'flippin', 'flipping', 'fricking', 'friggin', 'frigging', 'frightfully', 'fucking', 'fully',
                    'fully', 'greatly', 'hardly', 'highly', 'hugely', 'incredibly', 'insanely', 'intensely',
                    'just enough', 'kind of', 'kinda', 'less', 'literally', 'little', 'majorly', 'mightily',
                    'more', 'most', 'much', 'outrageously', 'particularly', 'phenomenally', 'preciously', 'pretty',
                    'purely', 'quite', 'radically', 'rather', 'really', 'remarkably', 'ridiculously', 'seriously',
                    'slightly', 'so', 'so', 'strikingly', 'strongly', 'substantially', 'super', 'supremely',
                    'surpassingly', 'terribly', 'terrifically, fabulously', 'thoroughly', 'too', 'totally',
                    'tremendously', 'unbelievably', 'unusually', 'utterly', 'very']

# =============================================================================
# intensifier_list.sort()
# print(intensifier_list)
# =============================================================================

sarcastic_slangs = {"ayfkmwts" : "are you fucking kidding me",
                    "fubar" : "fucked up beyond all repair",
                    "ffs" : "for fuck‘s sake",
                    "gmafb" : "give me a fucking break",
                    "gtfooh" : "get the fuck out of here",
                    "kyso" : "knock your socks off",
                    "ht" : "heard through",
                    "lhh" : "laugh hella hard",
                    "nfw" : "no fucking way",
                    "lmao" : "laughing my ass off",
                    "jk" : "just kidding",
                    "lol" : "laugh out loud",
                    "omfg" : "oh my fucking god",
                    "rtfm" : "read the fucking manual",
                    "snafu" : "situation normal, all fucked up",
                    "stfw" : "search the fucking web!",
                    "sob" : "son of a bitch",
                    "smdh" : "shaking my damn head",
                     "stf" : "shut the fuck",
                     "stfu" : "shut the fuck up",
                     "tldr" : "too long did not read",
                     "tl;dr" : "too long did not read",
                     "bts" : "behind the scenes",
                     "rofl" : "rolling on the floor laughing",
                     "roflmao" : "rolling on the floor laughing my ass off",
                     "tbbh" : "to be brutally honest",
                     "fml":"fuck my life",
                     "wtf":"what the fuck",
                     "wth":"what the hell",
                     "hella":"hell of a"
                    }
manual_stopwords = ['b', "'s", "'m", 'u', 'ca', "'re"]
negate_words = {
    "n't",
    "aint",
    "arent",
    "cannot",
    "cant",
    "couldnt",
    "darent",
    "didnt",
    "doesnt",
    "ain't",
    "aren't",
    "can't",
    "couldn't",
    "daren't",
    "didn't",
    "doesn't",
    "dont",
    "hadnt",
    "hasnt",
    "havent",
    "isnt",
    "mightnt",
    "mustnt",
    "neither",
    "don't",
    "hadn't",
    "hasn't",
    "haven't",
    "isn't",
    "mightn't",
    "mustn't",
    "neednt",
    "needn't",
    "never",
    "no",
    "not",
    "none",
    "nope",
    "nor",
    "not",
    "nothing",
    "nowhere",
    "oughtnt",
    "shant",
    "shouldnt",
    "uhuh",
    "wasnt",
    "werent",
    "oughtn't",
    "shan't",
    "shouldn't",
    "uh-uh",
    "wasn't",
    "weren't",
    "without",
    "wont",
    "wouldnt",
    "won't",
    "wouldn't",
    "rarely",
    "seldom",
    "despite",
    "scarcely",
    "less",
    "little",
    "hardly"
    }